server:
  port: 8081

spring:
  application:
    name: identity
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/identity?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: ${DB_USER:app}
    password: ${DB_PASSWORD:app_local_only}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis_local_only}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

jwt:
  access-key: ${ACCESS_KEY}
  refresh-key: ${REFRESH_KEY}
  accessTokenExp: 900000 # 15분
  refreshTokenExp: 1209600000 # 2주

admin:
  email: ${ADMIN_EMAIL:admin@admin.com}
  password: ${ADMIN_PASSWORD:admin}
