spring:
  cloud:
    gateway:
      routes:
        - id: identity
          uri: http://identity:8081
          predicates:
            - Path=/api/auth/**
        - id: payment
          uri: http://payment:8083
          predicates:
            - Path=/api/exhibitor/payments/**
        - id: reservation
          uri: http://reservation:8084
          predicates:
            - Path=/api/admin/reservation/**,/api/customer/**
        - id: expo
          uri: http://expo:8082
          predicates:
            - Path=/api/admin/**,/api/exhibitor/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${FRONT_ORIGIN}
            allowedMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: true
