apply plugin: 'java-library'

tasks.named('bootJar') { enabled = false }
tasks.named('jar') { enabled = true }

dependencies {
    api 'com.fasterxml.jackson.core:jackson-annotations'

    api         'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    compileOnly 'org.springframework:spring-web'
    compileOnly 'org.springframework:spring-webmvc'
    compileOnly 'org.springframework.data:spring-data-commons'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    compileOnly 'org.slf4j:slf4j-api'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    compileOnly 'com.fasterxml.jackson.core:jackson-databind'
}
